version: '3.8'

services:
  train:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ipc: host
    build: .
    volumes:
      # Override these in a override yaml as needed
      # Output save directory
      - /tmp/save_dir:/save_dir
      # Data Directory - filling with some placeholder. replace in override
      # The absolute path mounted to should also be relected in the csv
      - /CheXpert-v1.0-small:/CheXpert-v1.0-small
      # csv labels
      - /CheXpert-v1.0-small/train.csv:/Path/to/train.csv:ro
      - /CheXpert-v1.0-small/valid.csv:/Path/to/dev.csv:ro
    entrypoint: '/bin/bash -c "python bin/train.py config/example.json /save_dir --num_workers $$(nproc) --logtofile True"'
